apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260517-155135-vz9uvzuutbrs-service
spec:
  selector:
    app: enterprise-system-20260517-155135-vz9uvzuutbrs
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
